mpirun -n 1 -perhost 1 python asset_min.py
mpirun -n 2 -perhost 2 python asset_min.py
mpirun -n 4 -perhost 4 python asset_min.py
mpirun -n 8 -perhost 8 python asset_min.py
mpirun -n 16 -perhost 16 python asset_min.py
mpirun -n 32 -perhost 32 python asset_min.py
mpirun -n 64 -perhost 64 python asset_min.py
mpirun -n 128 -perhost 128 python asset_min.py
mpirun -n 256 -perhost 256 python asset_min.py
mpirun -n 1 -perhost 1 python asset_min.py
mpirun -n 2 -perhost 2 python asset_min.py
mpirun -n 4 -perhost 4 python asset_min.py
mpirun -n 8 -perhost 8 python asset_min.py
mpirun -n 16 -perhost 16 python asset_min.py
mpirun -n 32 -perhost 32 python asset_min.py
mpirun -n 64 -perhost 64 python asset_min.py
mpirun -n 128 -perhost 128 python asset_min.py
mpirun -n 256 -perhost 256 python asset_min.py
mpirun -n 1 -perhost 1 python asset_min.py
mpirun -n 2 -perhost 2 python asset_min.py
mpirun -n 4 -perhost 4 python asset_min.py
mpirun -n 8 -perhost 8 python asset_min.py
mpirun -n 16 -perhost 16 python asset_min.py
mpirun -n 32 -perhost 32 python asset_min.py
mpirun -n 64 -perhost 64 python asset_min.py
mpirun -n 128 -perhost 128 python asset_min.py
mpirun -n 256 -perhost 256 python asset_min.py
mpirun -n 1 -perhost 1 python asset_min.py
mpirun -n 2 -perhost 2 python asset_min.py
mpirun -n 4 -perhost 4 python asset_min.py
mpirun -n 8 -perhost 8 python asset_min.py
mpirun -n 16 -perhost 16 python asset_min.py
mpirun -n 32 -perhost 32 python asset_min.py
mpirun -n 64 -perhost 64 python asset_min.py
mpirun -n 128 -perhost 128 python asset_min.py
mpirun -n 256 -perhost 256 python asset_min.py
mpirun -n 1 -perhost 1 python asset_min.py
mpirun -n 2 -perhost 2 python asset_min.py
mpirun -n 4 -perhost 4 python asset_min.py
mpirun -n 8 -perhost 8 python asset_min.py
mpirun -n 16 -perhost 16 python asset_min.py
mpirun -n 32 -perhost 32 python asset_min.py
mpirun -n 64 -perhost 64 python asset_min.py
mpirun -n 128 -perhost 128 python asset_min.py
mpirun -n 256 -perhost 256 python asset_min.py
